version: "3"
services:
  chroma:
    image: chromadb/chroma:0.5.23
    ports:
      - "8000:8000"
  rag_admin_app:
    image: thesis_rag_admin:latest
    ports:
      - "8502:8502"
    environment:
      EMBEDDING_MODEL: mxbai-embed-large
      OLLAMA_HOST: http://192.168.0.27:11434
      CHROMADB_HTTPS_ADDRESS: 192.168.0.27
      CHROMADB_PORT: 8000
      CHROMADB_COLLECTION: scientific_papers
  rag_chat_app:
    image: rag_thesis:latest
    ports:
      - "8504:8504"
    volumes:
      - type: bind
        source: F:\\Dokumente\\rag_logs
        target: /thesis_rag/logs
    environment:
      EMBEDDING_MODEL: mxbai-embed-large
      OLLAMA_HOST: http://192.168.0.27:11434
      CHROMADB_HTTPS_ADDRESS: 192.168.0.27
      CHROMADB_PORT: 8000
      CHROMADB_COLLECTION: scientific_papers
      RETRIEVER_K_NUMBER: 20
      RETRIEVER_RELEVANCE_SCORE: 0.4
      LLM_MODEL: llama3.2:3b




